### ISSUE TITLE
Nested sandbox.zarr in 00_xenium_and_visium.ipynb

### ISSUE THREAD

**Issue by melonora** [scverse/spatialdata-notebooks#36] opened 2023-06-26 23:44 UTC
The `LANDMARKS_SDATA_PATH` is set to `GENERATED_DATA_PATH / "sandbox.zarr"` in the notebook. However when downloading and unzipping the data the sandbox.zarr directory contains sandbox.zarr itself. This can cause users who don't know this to get an error as the upper level is not a valid .zarr.

**Comment by kevinyamauchi** [comment] 2023-06-27 12:26
@LucaMarconato , what is your preferred fix here? I think just adding a note about this in a markdown cell would be sufficient. Thoughts?

**Comment by LucaMarconato** [comment] 2023-06-27 22:28
@melonora thanks for reporting.

This is the intended behavior, the user should place the `sandbox.zarr` file in the path `GENERATED_DATA`, which is `spatialdata-sandbox/generated_data/xenium_visium_integration`.

In the notebooks it's written to make this path discoverable via symlinks, so as a user I think I would be aware that I need to place the unzipped file to the right place. 

Anyway, to avoid confusion, I will add another note in the notebook when defining `GENERATED_DATA_PATH / "sandbox.zarr"` saying to the user that the files needs to be placed to the right location.

**Comment by LucaMarconato** [comment] 2023-06-27 22:30
But just to be sure that I understood your concern correctly, here also the `BC_atlas_we.h5ad` and `visium_copyKat.h5ad` needs to be placed to the right location.

![image](https://github.com/scverse/spatialdata-notebooks/assets/2664412/4a476d38-b7bb-4e7b-94f3-5dc240943328)

Why do you think that extra care needs to be placed to `sandbox.zarr`?

**Comment by LucaMarconato** [comment] 2023-06-27 22:31
Ah! I think I get it! One may expect that `sandbox.zarr` would expand to `spatialdata-sandbox`, but `sandbox.zarr` was a bad chosen name that I never changed thereafter. A better name is `manual_annotations.zarr`. I will open an issue to rename the file.

**Comment by LucaMarconato** [comment] 2023-06-27 22:34
Open the issue here: https://github.com/scverse/spatialdata-notebooks/issues/39, I close this issue because the problem is not about nesting but about a poorly chosen name.

**Closed by LucaMarconato** 2023-06-27 22:34 UTC

**Comment by melonora** [comment] 2023-06-28 08:23
it might be poorly choosen as well, but right now also when downloading you get this:
`sandbox.zarr/sandbox.zarr` where the top level `sandbox.zarr` is not a valid zarr and you indicate in the notebook that this is the level that will be read as zarr file, which causes an error.

**Comment by kevinyamauchi** [comment] 2023-06-28 11:17
> For the record this is what you get:
Yeah, I've seen that as well. For now, I think we just need a simple comment in the notebook explaining the issue.

**Comment by LucaMarconato** [comment] 2023-06-28 11:57
Ah ok I understand now. I can't reproduce this with macOS (both extracting using the finder or using `unzip`). I think it's Windows specific but I will now add a note in the notebook about that.
